font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
disable_ligatures never

font_size 12.0
cursor_trail 3
cursor_blink_interval 0

window_padding_width 10

background_blur 1
opacity 0

selection_foreground none
selection_background #28344a

# Window borders
active_border_color #3d59a1
inactive_border_color #101014
bell_border_color #fceb53

# Tab bar
tab_bar_style fade
tab_fade 1
active_tab_foreground   #3d59a1
active_tab_background   #16161e
active_tab_font_style   bold
inactive_tab_foreground #787c99
inactive_tab_background #16161e
inactive_tab_font_style bold
tab_bar_background #101014

# Title bar
macos_titlebar_color #16161e

# Theme
include ./theme.conf
