foreground #c0cffa
background #192338

background_opacity 0.2

# Black
color0 #0b1215
color8 #0e0e10

# Red
color1 #dc0000
color9 #ff0000

# Green
color2  #9bf019
color10 #d2ff28

# Yellow
color3  #febe11
color11 #ffd544

# Blue
color4  #77f7f0
color12 #0077b6

# Magenta
color5  #7e0b48
color13 #a10b56

# Cyan
color6  #00bcd4
color14 #4dd0e1

# White
color7  #c0cffa
color15 #ffffff

# Cursor
cursor #c0cffa
cursor_text_color #af2529

# URL
url_color #a0e0c8
